name: Mirror to Gitee Repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
  workflow_dispatch:

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_DEPLOY_KEY }}
        with:
          source-repo: 'git@github.com:zhenfeng95/community-pc.git'
          destination-repo: 'git@gitee.com:zhenfeng95/community-pc.git'
